name: Check Domain Expiry

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:  # Allows manual triggering

jobs:
  check_expiry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check domain expiry
      uses: manippoudel/domain-expiry-monitor@main  
      with:
        domains: ${{ secrets.DOMAINS }}
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}